web:
  build: .
  dockerfile: Dockerfile.development
  volumes:
    - .:/champaign
    - ../sou-assets:/sou-assets
    - /champaign/node_modules/
    - /champaign/tmp/
    - /champaign/public/packs/
    - /champaign/public/packs-test/
    - /public/system/
  ports:
    - "3000:3000"
    - "8080:8080"
  links:
    - db
    - redis
  environment:
    PG_USERNAME: postgres
    PG_HOST: db
    PG_PORT: 5432

  env_file:
    - .env-docker

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign

redis:
  image: redis
  ports:
    - "6379"
