FROM starefossen/ruby-node:2-8

RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64
RUN chmod +x /usr/local/bin/dumb-init

ENV APP_ROOT /champaign

RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 20 --retry 3

COPY package.json yarn.lock $APP_ROOT/
RUN yarn

COPY . $APP_ROOT/

EXPOSE 3000 8080

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["bundle", "exec", "foreman", "start"]
